encryptionsalt: v1:iD+KtU2xrac=:v1:kxD0otFlH57sI+gN:Deuadl5lTaNEsyLqN+PmZGmJQKLHzw==
config:
  minerva:github_repo: https://github.com/GowthamPrakaash/minerva
  minerva:github_token:
    secure: v1:v4cdxicEIBUbF8PO:0G5MJZJ0xIDk40g6N8M+JYotg5MD5COIJGUA2Xh76FTJz03AU5e94i8xJqRPtNl2Zxx1APo/NH4=
  minerva:auth_secret:
    secure: v1:tjWOHeGQLHBsV8JD:0jwEkxly0RQFRq9f6P2P+qSDmdVn/A3+bjCrpNdExBHJfT+JIbYNq6K+KwleNqXA3OHMTswlHuVrbgCKIvqzQKjyGE8EArLCnEKs/acZfYB+GCvkt8d/WUg2XOhbev+C9EjuHtE=
  minerva:auth_google_id:
    secure: v1:zjgIHO0vScf1CHM3:xPsAqeqLR/GHppY6Fv+hHxuVo+omDfu8MsIBm7QRCm+xknG+oVhxM3YqB/x7IQRFUIaYt9fos+aRWMxxHXPL46WDKaSjz+IYNiDF0V1DPDgBxs1La/ZmQw==
  minerva:auth_google_secret:
    secure: v1:nvQkU0kYqJ9gt+78:raH4wghgou+W8mFYwE0GN8VaPP+T+t7goYetzaWbPU0Oks5jr6L1Lc60Kz76iwar9vv5
=======
    secure: v1:iAWigbuDh+iHaXIE:bagTyRqlOe8jsHa9bAkyPQ==
  minerva:auth_google_id:
    secure: v1:Tn0TBCMPbl0Hn8tl:lf+zD2t5RaKo3wT33EtYEw==
  minerva:auth_google_secret:
    secure: v1:p94t20amnsoaeVLV:PJAWyTBmHfnndz7kVcZuXg==
>>>>>>> 6861e43f53d787e873060d6fa1923ea1a9b0ced5
  minerva:deploy_core: "true"
  minerva:deploy_dashboard: "true"
  minerva:deploy_ingestion: "true"
